namespace Aiursoft.Apkg.Sdk.Models;

/// <summary>
/// The manifest embedded inside a .apkg archive (format version 2).
/// Auto-generated by <c>apkg publish</c>; consumed by the Apkg server.
///
/// A hybrid .apkg package targets exactly ONE Distro, ONE PackageName, and ONE Component.
/// Within a single upload you may mix different Versions, Suites, and Architectures.
/// All entries MUST share the same Distro and Component — mixing is rejected.
/// </summary>
[System.Xml.Serialization.XmlRoot("ApkgPackage")]
public class ApkgPackageManifest
{
    [System.Xml.Serialization.XmlAttribute("FormatVersion")]
    public int FormatVersion { get; set; } = 2;

    [System.Xml.Serialization.XmlElement("Name")]
    public string Name { get; set; } = string.Empty;

    [System.Xml.Serialization.XmlElement("Distro")]
    public string Distro { get; set; } = "ubuntu";

    [System.Xml.Serialization.XmlElement("Component")]
    public string Component { get; set; } = "main";

    [System.Xml.Serialization.XmlElement("Maintainer")]
    public string Maintainer { get; set; } = string.Empty;

    [System.Xml.Serialization.XmlElement("Description")]
    public string Description { get; set; } = string.Empty;

    [System.Xml.Serialization.XmlElement("Homepage")]
    public string Homepage { get; set; } = string.Empty;

    [System.Xml.Serialization.XmlElement("License")]
    public string License { get; set; } = "MIT";

    [System.Xml.Serialization.XmlArray("Entries")]
    [System.Xml.Serialization.XmlArrayItem("Entry")]
    public List<ApkgPackageEntry> Entries { get; set; } = [];
}

/// <summary>Maps one .deb file to an APT suite and architecture.</summary>
public class ApkgPackageEntry
{
    /// <summary>Filename inside the .apkg archive, e.g. "pkgname_1.0.0_jammy_amd64.deb".</summary>
    [System.Xml.Serialization.XmlElement("DebFile")]
    public string DebFile { get; set; } = string.Empty;

    [System.Xml.Serialization.XmlElement("Suite")]
    public string Suite { get; set; } = string.Empty;

    [System.Xml.Serialization.XmlElement("Architecture")]
    public string Architecture { get; set; } = "amd64";
}
