using System.Text;
using Aiursoft.Apkg.Entities;
using Aiursoft.Apkg.Services;
using Aiursoft.Apkg.Services.FileStorage;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Aiursoft.Apkg.Controllers;

[AllowAnonymous]
[ApiController]
public class AptMirrorController(
    AptMirrorService aptMirrorService,
    ApkgDbContext dbContext,
    FeatureFoldersProvider folders) : ControllerBase
{
    private string BucketsRoot => folders.GetBucketsFolder();

    [HttpGet]
    [Route("artifacts/{distro}/dists/{suite}/{**path}")]
    [Route("artifacts/repo/{repoName}/dists/{suite}/{**path}")]
    [Route("artifacts/dists/{suite}/{**path}")]
    public async Task<IActionResult> GetDists(
        [FromRoute] string? distro,
        [FromRoute] string? repoName,
        [FromRoute] string suite,
        [FromRoute] string path)
    {
        repoName ??= suite;
        path = path.TrimStart('/');

        var repoQuery = dbContext.AptRepositories
            .AsNoTracking()
            .Include(r => r.PrimaryBucket)
            .AsQueryable();

        if (!string.IsNullOrWhiteSpace(distro))
        {
            repoQuery = repoQuery.Where(r => r.Distro == distro);
        }

        var repo = await repoQuery.FirstOrDefaultAsync(r => r.Name == repoName || r.Suite == suite);

        if (repo?.PrimaryBucket == null) return NotFound();

        var bucket = repo.PrimaryBucket;

        if (path.EndsWith("InRelease") && bucket.InReleaseContent != null)
            return ConditionalContent(bucket.InReleaseContent, bucket.SignedAt!.Value, "text/plain");
        if (path.EndsWith("Release") && bucket.ReleaseContent != null)
            return ConditionalContent(bucket.ReleaseContent, bucket.CreatedAt, "text/plain");

        if (path.Contains("Packages") || path.Contains("Contents"))
        {
            var localPath = Path.Combine(BucketsRoot, bucket.Id.ToString(), path);
            if (System.IO.File.Exists(localPath))
            {
                Response.Headers.CacheControl = "no-cache";
                return PhysicalFile(localPath, localPath.EndsWith(".gz") ? "application/x-gzip" : "text/plain", true);
            }
        }

        return NotFound();
    }

    [HttpGet]
    [Route("artifacts/certs/{name}")]
    public async Task<IActionResult> GetCert([FromRoute] string name)
    {
        var cert = await dbContext.AptCertificates
            .AsNoTracking()
            .FirstOrDefaultAsync(c => c.Name == name);

        if (cert == null) return NotFound();
        var fileName = $"{cert.Name}.asc";
        return File(Encoding.UTF8.GetBytes(cert.PublicKey), "application/pgp-keys", fileName);
    }

    /// <summary>
    /// Suite-scoped pool endpoint.  Packages files generated by RepositorySyncJob rewrite
    /// pool Filenames to "pool/{suite}/main/…" so that APT constructs download URLs of the
    /// form ".../artifacts/{distro}/pool/{suite}/main/…".  Handling those here lets us pass
    /// the suite name to GetLocalPoolPath (via repoName), which scopes the CAS lookup to
    /// that suite's primary bucket and prevents cross-suite SHA256 mismatches.
    /// </summary>
    [HttpGet]
    [Route("artifacts/{distro}/pool/{suite}/{**path}")]
    public async Task<IActionResult> GetSuitePool(
        [FromRoute] string distro,
        [FromRoute] string suite,
        [FromRoute] string path)
    {
        var localPath = await aptMirrorService.GetLocalPoolPath(path, distro: distro, repoName: suite);
        if (localPath == null) return NotFound();

        return PhysicalFile(localPath, "application/vnd.debian.binary-package", true);
    }

    private IActionResult ConditionalContent(string content, DateTime lastModified, string contentType)
    {
        Response.Headers.LastModified = lastModified.ToString("R");
        Response.Headers.CacheControl = "no-cache";

        if (DateTime.TryParse(Request.Headers.IfModifiedSince, out var ifModifiedSince))
        {
            // Truncate to second precision — HTTP-date has no sub-second resolution
            if (lastModified <= ifModifiedSince.AddSeconds(1))
            {
                return StatusCode(304);
            }
        }

        return Content(content, contentType);
    }
}
